language: python
python:
- '3.3'
- '3.4'
install: python setup.py install
script: python setup.py test
deploy:
  provider: pypi
  user: kirillsulim
  password:
    secure: cZGj4N/GfLONTKNBZpyP62edJoPnw1piZUiMEyqPkF4T1XPwCNpLEITSCIX1TIHc9YFYfxBviayEpCOdhB6wk3SAc1bgULeqwA+RXzl9fYSKtmjHQnI38X4gqbp+/0MQsc5OulOj1kCUAsE1J1HxJ5YkdYz3jcU/Ngv0Fwg0aVwxVkbJ7iaQFs+NRtQ/ZZeFycQCCVZ7W8LM+6+smC13A4ad6BqsSmP7/yTTi7a0Om0huygRtVwGrVaEL9ZwAYO9Np8vZtmFndMjRbr6VA6COf9vcbdUpNKoYIjkgMzhj6PKIsFOIqUzwPF3vHGWDEzB4JEsjbtHHsfXiG5QVYk1prvn4wOebuz4htyKE4aRfSeM5PcxnoAY+nvU1Nl4Z8wLIj/o80ehIVahMWerBA8AaAe12l1ZOaEIvsP9vR2vmENoiGza2rcPWwWQ9HEQ6CpVW5Fqr+rzapUl32neh1vNLoVHhmA9cVDmSZaukGHVFdCvUr9l073FQDt821nzcG8fI7GU/Z5zwpX9IQEI/fFkCcbLYbjEpGCq7g44bpI9eMfzpIRchw7so7Wi497GWDAUxfX1BpRl6cS3ifx2apJKIcLsjxP2kB2AbrtNu31tpe+piEcG/kzm2MbwrrgMqyDu174tJOjwJtPDBKr8NhRdyHg7xEbr+vEhfxxlQe+vFWU=
  on:
    tags: true
    repo: dogebuild/dogebuild-hello
